# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 00:13
from __future__ import unicode_literals

from django.db import migrations


def create_genres(apps, schema_editor):
    Genre = apps.get_model('flix', 'Genre')
    genres = ['Action', 'Adventure', 'Animation', "Children's", 'Comedy',
              'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir',
              'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller',
              'War', 'Western']

    for item in genres:
        temp = Genre(genre=item)
        temp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('flix', '0004_auto_20160820_1912'),
    ]

    operations = [
        migrations.RunPython(create_genres)
    ]
