# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 00:34
from __future__ import unicode_literals

from django.db import migrations


def connect_genres(apps, schema_editor):
    Movie = apps.get_model('flix', 'Movie')
    Genre = apps.get_model('flix', 'Genre')

    movies = Movie.objects.all()
    for movie in movies:
        old_genres = movie.genre.split("|")
        for item in old_genres:
            movie.genres.add(Genre.objects.get(genre=item))
        movie.save()


class Migration(migrations.Migration):

    dependencies = [
        ('flix', '0005_auto_20160820_1913'),
    ]

    operations = [
        migrations.RunPython(connect_genres)
    ]
