# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flix', '0006_auto_20160820_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
